CREATE TABLE IF NOT EXISTS books (
    serial_number   VARCHAR(6) PRIMARY KEY,
    title           TEXT NOT NULL,
    author          TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
    card_number     VARCHAR(6) PRIMARY KEY,
    name            TEXT
);

CREATE TABLE IF NOT EXISTS loans (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number   VARCHAR(6) NOT NULL REFERENCES books(serial_number) ON DELETE CASCADE,
    card_number     VARCHAR(6) NOT NULL REFERENCES clients(card_number) ON DELETE RESTRICT,
    borrowed_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    returned_at     TIMESTAMPTZ
);
